version: "3.7"

services:
  attrakttv:
    container_name: attrakttv
    # image: rocker/shiny
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    user: 'shiny'
    # Uncomment the lines below to disable application logs STDOUT output
    # environment:
    #   - APPLICATION_LOGS_TO_STDOUT=false
    ports:
      - '3839:3838'
    volumes:
      - 'shiny_logs:/var/log/shiny-server'
      - type: volume
        source: trakt_db
        target: /home/shiny
        volume:
          nocopy: true

volumes:
  shiny_logs:
  trakt_db:
    driver: local
    driver_opts:
      type: local
      device: ${trakt_db_path}
      o: bind
